title: AETHERION_OS
description: Système d’exploitation expérimental open source x86/x64
baseurl: "/www" # chemin GitHub Pages
url: "https://yasscode1234.github.io"
theme: cayman
markdown: kramdown

# Navigation
nav:
  - title: Accueil
    url: /
  - title: Démo
    url: /demo
  - title: Téléchargement
    url: /downloads
  - title: Roadmap
    url: /roadmap
